# deploy vsftpd
- hosts: testservers
  gather_facts: False
  vars:
    packages: vsftpd
    user: cici
  tasks:
    - name: install vsftpd
      yum: name={{ packages }} state=present
    - name: configuration file
      copy: src=/tmp/vsftpd.conf dest=/etc/vsftpd/
    - name: add ftp user
      user: name={{ user }} state=present createhome=yes home=/cici shell=/sbin/nologin password=$1$gFL14xgE$hUv92COBQGjWn2ZJPKcTS0
    - name: setup chroot_list 1
      file: name=/etc/vsftpd/chroot_list state=touch
    - name: setup chroot_list 2
      lineinfile: dest=/etc/vsftpd/chroot_list line="{{ user }}"
    - name: setting selinux
      command: /usr/sbin/setsebool -P ftp_home_dir on
    - name: setting iptables for ftp
      command: iptables -I INPUT -p tcp --dport=21 -j ACCEPT
    - name: saving iptables configuration
      command: /etc/init.d/iptables save
      notify:
      - restart vsftpd
  handlers:
    - name: restart vsftpd
      service: name=vsftpd state=restarted
